# 파이썬 기초3 : AI 모델링과 데이터 사이언스를 위한 기초 과정
* 본 과정은 파이썬 초심자을 위한 과정으로 AI 모델링과 데이터 사이언스를 위해 꼭 필요한 지식에 대해 배울 수 있습니다.
* 본 과정을 모두 마칠 무렵이면 여러분은 파이썬으로 데이터를 다룰 수 있게될 겁니다.
* 파이썬에 대한 모든 것을 다루지는 않습니다. 처음 AI 모델링과 데이터 사이언스를 시작할 때 꼭 필요한 내용을 중심으로 준비했습니다.

## 3. Numpy로 배열 다루기1
* 이번 시간에는 데이터 사이언스에서 많이 활용되는 배열을 다룰 수 있도록 도와주는 Numpy에 대해서 다루어 볼 예정입니다.
* 특히 Numpy를 활용해서 배열을 생성하고 슬라이싱하고 인덱싱하는 방법에 대해 알아보겠습니다.

* Numpy 공식 Document
    * https://numpy.org/

### Q1. Numpy는 무엇일까요?

#### Chat GPT에게 물어봅시다.

> Numpy는 무엇인가요?(Query : Numpy는 무엇인가요?)
> * NumPy는 Python에서 과학 계산을 위한 핵심 패키지입니다. NumPy는 다차원 배열 객체, 마스크된 배열 및 행렬과 같은 여러 파생 객체, 그리고 수학 연산, 논리 연산, 형태 조작, 정렬, 선택, 입출력 등 배열에 대한 빠른 연산을 수행하기 위한 다양한 루틴을 제공하는 Python 라이브러리입니다[1].

NumPy는 Python 프로그래밍 언어를 위한 라이브러리로, 큰 다차원 배열과 행렬을 지원하며, 이러한 배열에 대해 고수준의 수학 함수 컬렉션을 제공합니다[2].

NumPy는 배열을 다루기 위해 사용되는 Python 라이브러리로, 선형 대수, 푸리에 변환, 행렬 등의 작업에도 사용됩니다. NumPy는 2005년에 Travis Oliphant에 의해 개발되었으며, 오픈 소스 프로젝트로 무료로 사용할 수 있습니다. NumPy는 Numerical Python의 약자입니다[3].

따라서, NumPy는 Python에서 과학적인 계산을 위한 핵심 패키지로, 다차원 배열과 행렬을 다루고 빠른 연산을 수행하는 데 사용되는 라이브러리입니다.

> Numpy는 어떤 기능이 있나요?(Query : Numpy의 기능 중 대표적인 세 가지만 알려주세요)
> * ndarray.shape: 배열의 각 축(axis)의 크기를 나타내는 속성입니다. 이 속성은 배열의 차원을 파악하고 배열의 형태를 이해하는 데 도움을 줍니다[1].
> * ndarray.ndim: 배열의 축 수(차원)를 나타내는 속성입니다. 다차원 배열을 다룰 때 몇 개의 축이 있는지 파악할 수 있습니다[1].
> * ndarray.dtype: 배열의 요소(element)의 데이터 타입을 나타내는 속성입니다. 배열의 요소가 어떤 데이터 타입을 갖고 있는지 알 수 있습니다. 예를 들어, 정수, 부동소수점, 문자열 등의 데이터 타입을 가질 수 있습니다[1].

##### + 본격적인 실습 이전에  Numpy를 설치하겠습니다.

In [1]:
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: C:\Users\tdc81\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


### Q2. Numpy로 배열은 어떻게 생성하나요?
* Query : Numpy로 배열을 생성하는 방법에 대해서 알려주세요

#### 1. Chat GPT가 알려준 방법을 여기에 적어주세요.

In [2]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy의 OOO을 활용해서 배열을 생성하는 예시코드 만들어 주세요)
import numpy as np

# 크기가 (2, 3)인 2D 배열 생성
zeros_array = np.zeros((2, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]]


#### 2. Chat GPT가 알려준 방법을 여기에 적어주세요.

In [3]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy의 OOO을 활용해서 배열을 생성하는 예시코드 만들어 주세요)
import numpy as np

# 크기가 (3, 2)인 2D 배열 생성
ones_array = np.ones((3, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### 3. Chat GPT가 알려준 방법을 여기에 적어주세요.

In [4]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy의 OOO을 활용해서 배열을 생성하는 예시코드 만들어 주세요)
import numpy as np

# 크기가 (2, 2)이고 값이 7인 배열 생성
full_array = np.full((2, 2), 7)
print(full_array)


[[7 7]
 [7 7]]


#### 4. Chat GPT가 알려준 방법을 여기에 적어주세요.

In [5]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy의 OOO을 활용해서 배열을 생성하는 예시코드 만들어 주세요)
import numpy as np

# 크기가 (3, 3)인 단위 행렬 생성
eye_array = np.eye(3)
print(eye_array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Q3. Numpy로 다차원 배열은 어떻게 생성하나요?
* Query : Numpy로 다차원 배열을 생성하는 방법에 대해서 알려주세요

#### 1. Chat GPT가 알려준 방법을 여기에 적어주세요.

In [ ]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy의 OOO을 활용해서 배열을 생성하는 예시코드 만들어 주세요)
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


#### 2. Chat GPT가 알려준 방법을 여기에 적어주세요.

In [6]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy의 OOO을 활용해서 배열을 생성하는 예시코드 만들어 주세요)
import numpy as np

# Create a 2D array filled with zeros
zeros_arr = np.zeros((3, 4))
print(zeros_arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 3. Chat GPT가 알려준 방법을 여기에 적어주세요.

In [7]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy의 OOO을 활용해서 배열을 생성하는 예시코드 만들어 주세요)
import numpy as np

# Create a 2D array filled with zeros
zeros_arr = np.zeros((3, 4))
print(zeros_arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 4. Chat GPT가 알려준 방법을 여기에 적어주세요.

In [8]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy의 OOO을 활용해서 배열을 생성하는 예시코드 만들어 주세요)
import numpy as np

# Create a 3D array with uninitialized values
empty_arr = np.empty((2, 3, 4))
print(empty_arr)


[[[6.23042070e-307 4.67296746e-307 1.69121096e-306 8.45595971e-307]
  [1.89146896e-307 7.56571288e-307 3.11525958e-307 1.24610723e-306]
  [1.37962320e-306 1.29060871e-306 2.22518251e-306 1.33511969e-306]]

 [[1.78022342e-306 1.05700345e-307 1.11261027e-306 1.11261502e-306]
  [1.42410839e-306 7.56597770e-307 6.23059726e-307 1.42419530e-306]
  [7.56599128e-307 1.78022206e-306 8.34451503e-308 2.22507386e-306]]]


#### 5. Chat GPT가 알려준 방법을 여기에 적어주세요.

In [ ]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy의 OOO을 활용해서 배열을 생성하는 예시코드 만들어 주세요)


### Q4. Numpy로 배열 슬라이싱은 어떻게 생성하나요?
* Query : Numpy로 배열을 슬라이싱하는 방법에 대해서 알려주세요

> 배열 슬라이싱은 어떤 개념인가요?
> * 넘파이는 파이썬에서 데이터를 다루는 데 사용되는 라이브러리로, 배열에 대한 다양한 기능을 제공합니다.
배열 슬라이싱은 배열의 특정 부분을 선택하여 가져오는 방법입니다. 아래의 예시를 통해 슬라이싱의 개념을 
이해해보겠습니다 배열 인덱싱(Indexing)은 배열에서 특정 요소에 접근하는 것을 의미합니다. 
슬라이싱(Slicing)은 배열에서 일부분을 잘라내어 가져오는 것을 의미합니다. 이 두 가지 개념을 
함께 사용하여 배열을 다양한 방식으로 조작할 수 있습니다.

#### 1. 1차원 배열 슬라이싱

In [11]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy를 활용해서 1차원 배열을 슬라이싱하는 예시코드 만들어 주세요)
import numpy as np

# 1차원 배열 생성
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 배열 슬라이싱
sliced_arr = arr[2:6]  # 인덱스 2부터 5까지 슬라이싱

# 슬라이싱된 배열 출력
print(sliced_arr)


[3 4 5 6]


#### 2. 2차원 배열 슬라이싱

In [12]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy를 활용해서 2차원 배열을 슬라이싱하는 예시코드 만들어 주세요)
import numpy as np

# Create a 2-dimensional array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Slice the array to get a subarray
subarray = arr[1:3, 1:3]
print(subarray)


[[ 6  7]
 [10 11]]


### Q5. Numpy로 배열 인덱싱은 어떻게 생성하나요?
* Query : Numpy로 배열을 인덱싱하는 방법에 대해서 알려주세요

> 배열 인덱싱은 어떤 개념인가요?
> * 기본 인덱싱: 인덱싱을 사용하여 NumPy 배열의 개별 요소 또는 요소 범위에 액세스할 수 있습니다. 예를 들어 배열 arr이 있고 인덱스 3의 요소에 액세스하려는 경우 arr[3]을 사용할 수 있습니다. 다양한 요소에 액세스하려면 슬라이싱을 사용할 수 있습니다. 예를 들어 arr[1:4]는 인덱스 1에서 3까지의 요소를 제공합니다. [[1]

#### 1. 기본 인덱싱

In [13]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy를 활용해서 기본 인덱싱하는 예시코드 만들어 주세요)
import numpy as np

# 1차원 배열 생성
data = np.array([1, 2, 3])

# 특정 인덱스의 값 출력
print(data[1])  # 출력: 2

# 범위 인덱싱 (슬라이싱)
print(data[0:2])  # 출력: [1 2]

# 인덱스 1부터 끝까지 출력
print(data[1:])  # 출력: [2 3]

# 음수 인덱스를 사용하여 뒤에서부터 인덱싱
print(data[-2:])  # 출력: [2 3]


2
[1 2]
[2 3]
[2 3]


#### 2. 팬시 인덱싱

In [14]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy를 활용해서 팬시 인덱싱하는 예시코드 만들어 주세요)
import numpy as np

# 1차원 배열 생성
array1d = np.array([10, 20, 30, 40, 50])

# Fancy indexing을 사용하여 특정 인덱스의 값들을 추출
indices = [1, 3, 4]
result = array1d[indices]

# 결과 출력
print(result)  # 출력: [20 40 50]


[20 40 50]


#### 3. 불린 인덱싱

In [15]:
# Chat GPT가 알려준 예시코드로 실습을 해봅시다.(Query : Numpy를 활용해서 불린 인덱싱하는 예시코드 만들어 주세요)
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Accessing elements using index
print(arr[0])  # Output: 1
print(arr[2])  # Output: 3

# Modifying elements using index
arr[3] = 10
print(arr)  # Output: [1 2 3 10 5]

# Indexing with a boolean array
bool_arr = np.array([True, False, True, False, True])
print(arr[bool_arr])  # Output: [1 3 5]

# Indexing with a slice
slice_arr = arr[1:4]
print(slice_arr)  # Output: [2 3 10]


1
3
[ 1  2  3 10  5]
[1 3 5]
[ 2  3 10]


## Summary
* 이번 시간에는 Numpy를 활용해서 배열을 생성하고 슬라이싱하고 인덱싱하는 방법에 대해서 다루어 봤습니다.
* 다음 시간에는 Numpy로 배열의 형태를 확인 및 변경하고 타입을 확인하고 연산과 함수를 활용하는 방법에 대해서 다루어 보겠습니다.